import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Control } from "./Control";

export const metadata: Metadata = {
  title: "Web Tutorials",
  description: "Generated by Sindbad",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const resp = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/topics`, {
    cache: "no-store",
  });
  const topics = await resp.json();

  return (
    <html>
      <body>
        <h1>
          <a href="/">WEB</a>{" "}
        </h1>
        <ol>
          {topics.map((topic: any) => (
            <li key={topic.id}>
              <Link href={`/read/${topic.id}`}>{topic.title}</Link>
            </li>
          ))}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
